'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {BookOpen,Search,LockKeyhole,ArrowUpRight,Bookmark,Download,Check,LoaderCircle,LogOut,RefreshCw} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem} from '@/components/ui/combobox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {supabase} from '@/lib/supabase';
import {SUPABASE_URL} from '@/lib/config';
import {genders,caseNames,questions,type Gender,type Lookup,type Saved,type Source} from '@/lib/types';
import {suggest} from '@/lib/suggestions';
import {exportData} from '@/lib/exports';
import {registerLookup} from '@/lib/webmcp';

const baseEndpoint=()=>typeof window!=='undefined'&&(window as unknown as {PAGES_BUILD?:boolean}).PAGES_BUILD?SUPABASE_URL+'/functions/v1/dictionary':'/api/dictionary';
async function api(word:string,action='lookup',signal?:AbortSignal){
 const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Pro ověření se přihlaste ke svému slovníku.');
 const response=await fetch(baseEndpoint()+'?'+new URLSearchParams({word,action}),{headers:{Authorization:'Bearer '+session.access_token},signal});
 const json=await response.json().catch(()=>({error:'Služba není dostupná. Ověřte nasazení funkce dictionary.'})) as Lookup & {suggestions?:string[];error?:string;message?:string};if(!response.ok)throw new Error(json.error||json.message||'Ověření se nezdařilo.');return json;
}
function SourceTitle({source,name}:{source:Source;name:string}){return <div className="sourceheading"><span className={'dot '+(source.status==='ok'?'ok':'warn')}/><a href={source.url} target="_blank" rel="noreferrer">{name} <ArrowUpRight size={14}/></a><small>{source.status==='ok'?'Načteno':source.status==='error'?'Nedostupné':'Nenalezeno'}</small></div>}
function FormCell({source,n,index}:{source:Source;n:'singular'|'plural';index:number}){if(!source.entries.length)return <span className="missing">—</span>;return <>{source.entries.map((p,k)=><div key={k} className="formvariant">{source.entries.length>1&&<small className="sense">{p.lemma} · {p.gender?genders[p.gender]:'Rod neurčen'}</small>}{p[n][index]?.join(', ')||<span className="missing">—</span>}</div>)}</>}
function same(a:string[],b:string[]){return a.length>0&&b.length>0&&[...a].sort().join('|')===[...b].sort().join('|');}
function Comparison({result}:{result:Lookup}){
 const comparable=result.ijp.entries.length===1&&result.morphodita.entries.length===1&&result.ijp.entries[0].gender===result.morphodita.entries[0].gender;
 return <><div className="sourcegrid"><SourceTitle source={result.ijp} name="Internetová jazyková příručka"/><SourceTitle source={result.morphodita} name="MorphoDiTa · ÚFAL"/></div>
 <div className="comparison"><Table><TableHeader><TableRow><TableHead rowSpan={2}>Pád a otázka</TableHead><TableHead colSpan={2}>Internetová jazyková příručka</TableHead><TableHead colSpan={2}>MorphoDiTa</TableHead></TableRow><TableRow>{[0,1].flatMap(k=>[<TableHead key={k+'s'}>Jednotné číslo</TableHead>,<TableHead key={k+'p'}>Množné číslo</TableHead>])}</TableRow></TableHeader><TableBody>{caseNames.map((name,i)=><TableRow key={name}><TableCell><div className="casecell"><b>{i+1}</b><div><strong>{name}</strong><small>{questions[i]}</small></div></div></TableCell>{(['ijp','morphodita'] as const).flatMap(key=>(['singular','plural'] as const).map(n=>{const different=comparable&&!same(result.ijp.entries[0][n][i],result.morphodita.entries[0][n][i])&&(result.ijp.entries[0][n][i].length>0||result.morphodita.entries[0][n][i].length>0);return <TableCell key={key+n} className={different?'different':''}><FormCell source={result[key]} n={n} index={i}/></TableCell>}))}</TableRow>)}</TableBody></Table></div>
 <div className="tablenote"><span><i/> Odlišné nebo chybějící varianty u jednoznačných hesel</span><span>— Zdroj tvar neuvádí</span></div>
 {(['ijp','morphodita'] as const).map(key=>result[key].message&&<p className="notice" key={key}>{key==='ijp'?'Příručka':'MorphoDiTa'}: {result[key].message}</p>)}
 {result.morphodita.guessed&&<p className="notice">MorphoDiTa tyto tvary odhadla. Nejde o ověřené slovníkové heslo.</p>}
 <p className="fineprint">Varianty jsou zachovány podle zdrojů; příručka obsahuje další poznámky k použití. MorphoDiTa může vracet i řidší nebo nespisovné tvary. {result.morphodita.model&&`Model: ${result.morphodita.model}.`}</p></>;
}
export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[login,setLogin]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authError,setAuthError]=useState(''),[authBusy,setAuthBusy]=useState(false);
 const [word,setWord]=useState(''),[suggestions,setSuggestions]=useState<string[]>([]),[result,setResult]=useState<Lookup|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [saved,setSaved]=useState<Saved[]>([]),[savedBusy,setSavedBusy]=useState(false),[savedError,setSavedError]=useState(''),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false),[view,setView]=useState('lookup'),[gender,setGender]=useState('all');
 const requestId=useRef(0);const activeUser=useRef<string|undefined>(undefined);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const {data}=supabase.auth.onAuthStateChange((_,s)=>{setSession(s);setAuthReady(true);});return()=>data.subscription.unsubscribe()},[]);
 const refresh=useCallback(async()=>{const user=activeUser.current;if(!user)return;setSavedBusy(true);setSavedError('');try{const rows:Saved[]=[];for(let offset=0;;offset+=500){const {data,error}=await supabase.from('czech_words').select('id,word,result,updated_at').order('updated_at',{ascending:false}).range(offset,offset+499);if(error)throw error;rows.push(...data as Saved[]);if(data.length<500)break;}if(activeUser.current===user)setSaved(rows);}catch{if(activeUser.current===user)setSavedError('Slovník nelze načíst. Zkontrolujte připojení a dokončení nastavení Supabase.');}finally{if(activeUser.current===user)setSavedBusy(false)}},[]);
 useEffect(()=>{activeUser.current=session?.user.id;requestId.current++;setBusy(false);setResult(null);setSaved([]);setSavedError('');setMessage('');if(session)void refresh();},[session?.user.id,refresh]);
 useEffect(()=>{const local=suggest(word,saved.map(x=>x.word));setSuggestions(local);if(!session||word.trim().length<3)return;const controller=new AbortController();const timer=setTimeout(()=>{api(word.trim(),'suggest',controller.signal).then(data=>{if(!controller.signal.aborted)setSuggestions([...new Set([...(data.suggestions||[]),...local])].slice(0,8));}).catch(()=>{});},650);return()=>{clearTimeout(timer);controller.abort()}},[word,saved,session?.user.id]);
 const check=useCallback(async(value:string)=>{if(!value.trim())throw new Error('Zadejte slovo.');if(!session){setLogin(true);throw new Error('Pro ověření se přihlaste.');}const id=++requestId.current;setBusy(true);setError('');setMessage('');setView('lookup');try{const data:Lookup=await api(value);if(id===requestId.current){setResult(data);setWord(data.word);}return data;}catch(e){if(id===requestId.current)setError(e instanceof Error?e.message:'Ověření se nezdařilo.');throw e;}finally{if(id===requestId.current)setBusy(false)}},[session]);
 useEffect(()=>registerLookup(check),[check]);
 async function signIn(e:React.FormEvent){e.preventDefault();setAuthBusy(true);setAuthError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;setPassword('');setLogin(false);}catch{setAuthError('Přihlášení se nezdařilo. Zkontrolujte e-mail, heslo a připojení.')}finally{setAuthBusy(false)}}
 async function save(){if(!result||!session)return;const user=session.user.id;setSaving(true);setError('');try{const {error}=await supabase.from('czech_words').upsert({word:result.word,result,user_id:user,updated_at:new Date().toISOString()},{onConflict:'user_id,word'});if(error)throw error;if(activeUser.current===user){setMessage('Slovo bylo uloženo do vašeho slovníku.');await refresh()}}catch{setError('Uložení se nezdařilo. Zkontrolujte připojení a nastavení databáze.')}finally{setSaving(false)}}
 const visible=saved.filter(x=>gender==='all'||[...x.result.ijp.entries,...x.result.morphodita.entries].some(p=>p.gender===gender));
 async function runExport(format:'csv'|'xlsx'|'pdf'){setExporting(true);setError('');try{await exportData(format,view==='saved'?visible.map(x=>x.result):result?[result]:[])}catch(e){setError(e instanceof Error?e.message:'Export se nezdařil.')}finally{setExporting(false)}}
 const exportButtons=<div className="exports"><Download size={16}/>{(['csv','xlsx','pdf'] as const).map(format=><button className="textbutton" key={format} onClick={()=>runExport(format)} disabled={busy||exporting||(view==='saved'?!visible.length:!result)}>{format.toUpperCase()}</button>)}</div>;
 return <><header className="topbar"><a className="brand" href="./"><BookOpen/> české pády<span>OSOBNÍ SLOVNÍK</span></a>{session?<button className="secondary" onClick={async()=>{const {error}=await supabase.auth.signOut();if(error)setError('Odhlášení se nezdařilo. Zkuste to znovu.')}}><LogOut size={16}/><span>Odhlásit se</span></button>:<button className="secondary" onClick={()=>setLogin(true)} disabled={!authReady}><LockKeyhole size={16}/> Přihlásit se</button>}</header>
 <main className="workspace"><div className="eyebrow">SLOVO PO SLOVU</div><h1>Čeština ve všech pádech.</h1><p className="intro">Vyhledejte podstatné jméno. Porovnejte dva zdroje. Uložte si jeho tvary.</p>
 <section className="searchbox"><label htmlFor="word">Které slovo chcete skloňovat?</label><form onSubmit={e=>{e.preventDefault();void check(word).catch(()=>{})}}><Search className="searchicon"/><div className="wordcombobox"><Combobox items={suggestions} filter={null} inputValue={word} onInputValueChange={setWord} onValueChange={(value:string|null)=>{if(value)setWord(value)}}><ComboboxInput id="word" aria-label="Slovo ke skloňování" placeholder="Například kamarád, žena nebo město" showTrigger={false} autoComplete="off" maxLength={80}/><ComboboxContent><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><button type="submit" disabled={busy||!word.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:null}{busy?'Ověřuji…':'Ověřit slovo'} {!busy&&'→'}</button></form><small>Návrhy běžných a uložených slov, i bez diakritiky. Po přihlášení také opravy podle příručky.</small></section>
 <div className="rodlegend">{Object.entries(genders).map(([key,label])=><span key={key}>{label.split(' · ')[0]} <small>{label.split(' · ')[1]}</small></span>)}</div>
 <Tabs value={view} onValueChange={v=>setView(String(v))}><div className="viewbar"><TabsList variant="line"><TabsTrigger value="lookup"><Search size={16}/> Ověření slova</TabsTrigger><TabsTrigger value="saved"><Bookmark size={16}/> Můj slovník <span className="count">{saved.length}</span></TabsTrigger></TabsList>{exportButtons}</div>
 {error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success"><Check size={16}/>{message}</p>}
 <TabsContent value="lookup"><div aria-live="polite" aria-busy={busy}>{result?<section className={'resultcard '+(busy?'pending':'')}><div className="resulttop"><div><div className="eyebrow">{busy?'OVĚŘUJI NOVÉ SLOVO…':'VÝSLEDEK OVĚŘENÍ'}</div><h2>{result.word}</h2><div className="badges">{[...new Set([...result.ijp.entries,...result.morphodita.entries].map(x=>x.gender))].map(g=><span className="badge" key={g||'unknown'}>{g?genders[g]:'Rod neurčen'}</span>)}</div>{result.requested!==result.word&&<p className="correction">Příručka opravila „{result.requested}“ na „{result.word}“. Oba zdroje ověřují opravené heslo.</p>}</div><div className="savearea"><button onClick={save} disabled={saving||busy||!session||(!result.ijp.entries.length&&!result.morphodita.entries.length)}><Bookmark size={17}/>{saving?'Ukládám…':'Uložit slovo'}</button><small>{new Date(result.checkedAt).toLocaleString('cs-CZ')}</small></div></div><Comparison result={result}/></section>:<section className="welcome"><BookOpen size={32}/><h2>Každý pád na svém místě.</h2><p>Všech 7 pádů v jednotném i množném čísle, vedle sebe.</p><div className="examples">{['kamarád','žena','město','pes'].map(x=><button className="secondary" key={x} onClick={()=>{setWord(x);void check(x).catch(()=>{})}}>{x} <ArrowUpRight size={14}/></button>)}</div>{!session&&<p className="fineprint"><LockKeyhole size={14}/> Přihlaste se a otevřete svůj soukromý slovník.</p>}<div className="sources">Internetová jazyková příručka <span>+</span> MorphoDiTa · ÚFAL</div></section>}</div></TabsContent>
 <TabsContent value="saved"><section className="resultcard"><div className="savedtop"><h2>Můj slovník</h2><button className="secondary refreshbutton" aria-label="Znovu načíst slovník" title="Znovu načíst slovník" onClick={()=>refresh()} disabled={!session||savedBusy}><RefreshCw size={22} className={savedBusy?'spin':undefined}/></button></div>{session?<><p className="fineprint">{session.user.email} · Slova jsou přístupná pouze vašemu účtu.</p><Tabs value={gender} onValueChange={v=>setGender(String(v))}><TabsList className="genderfilters"><TabsTrigger value="all">Vše</TabsTrigger>{Object.entries(genders).map(([key,label])=><TabsTrigger key={key} value={key}>{label}</TabsTrigger>)}</TabsList></Tabs>{savedBusy?<p role="status">Načítám slovník…</p>:savedError?<p role="alert" className="notice error">{savedError}</p>:visible.length?<Table><TableHeader><TableRow><TableHead>Slovo</TableHead><TableHead>Rod podle zdrojů</TableHead><TableHead>Uloženo</TableHead><TableHead>Detail</TableHead></TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={row.id}><TableCell><strong>{row.word}</strong></TableCell><TableCell>{[...new Set([...row.result.ijp.entries,...row.result.morphodita.entries].map(p=>p.gender?genders[p.gender]:'Neurčeno'))].join(', ')}</TableCell><TableCell>{new Date(row.updated_at).toLocaleDateString('cs-CZ')}</TableCell><TableCell><button className="textbutton" onClick={()=>{requestId.current++;setBusy(false);setResult(row.result);setWord(row.word);setView('lookup');setError('');setMessage('Zobrazen uložený výsledek. Tlačítkem Ověřit slovo načtete aktuální tvary.')}}>Otevřít →</button></TableCell></TableRow>)}</TableBody></Table>:<div className="emptysaved"><Bookmark/><h3>{saved.length?'V tomto rodu zatím nejsou slova.':'Váš slovník čeká na první slovo.'}</h3><p>Vyhledejte slovo a zvolte „Uložit slovo“.</p></div>}<p className="fineprint">Export zahrnuje všechna slova z aktuálně vybraného rodu, oba zdroje a všech 14 pádových pozic.</p></>:<div className="emptysaved"><LockKeyhole/><h3>Váš slovník je soukromý.</h3><button onClick={()=>setLogin(true)}>Přihlásit se</button></div>}</section></TabsContent></Tabs>
 <footer><span>České pády · Váš prostor pro češtinu</span><div><a href="https://prirucka.ujc.cas.cz/" target="_blank" rel="noreferrer">ÚJČ AV ČR ↗</a><a href="https://ufal.mff.cuni.cz/morphodita" target="_blank" rel="noreferrer">MorphoDiTa / MorfFlex ↗</a></div></footer></main>
 <Dialog open={login} onOpenChange={setLogin}><DialogContent className="loginmodal"><DialogHeader><DialogTitle>Přihlášení do slovníku</DialogTitle><DialogDescription>Použijte účet ze Supabase Authentication. Váš slovník vidíte pouze vy.</DialogDescription></DialogHeader><form onSubmit={signIn}><label htmlFor="email">E-mail</label><input id="email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password">Heslo</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/>{authError&&<p role="alert" className="notice error">{authError}</p>}<button disabled={authBusy}>{authBusy?'Přihlašuji…':'Přihlásit se'}</button><p className="fineprint">Nemáte účet nebo potřebujete obnovit heslo? Obraťte se na správce slovníku.</p></form></DialogContent></Dialog></>;
}


